#!/usr/bin/env bash

IMG="colorcloud:latest"
CONTAINER_NAME=" --name transrvnet"

DOCKER_OPTS="$DOCKER_OPTS -v $SSH_AUTH_SOCK:/ssh-agent"
DOCKER_OPTS="$DOCKER_OPTS --env SSH_AUTH_SOCK=/ssh-agent"
DOCKER_OPTS="$DOCKER_OPTS -v /home/matheus/.ssh:/root/.ssh:ro"
DOCKER_OPTS="$DOCKER_OPTS --gpus all"
DOCKER_OPTS="$DOCKER_OPTS --ipc=host"
DOCKER_OPTS="$DOCKER_OPTS --network=host"
DOCKER_OPTS="$DOCKER_OPTS --rm"

echo $DOCKER_OPTS

docker run \
    $DOCKER_OPTS \
    $CONTAINER_NAME \
    $IMG \
