# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/colorcloud',
                'doc_host': 'https://AIR-UFG.github.io',
                'git_url': 'https://github.com/AIR-UFG/colorcloud',
                'lib_path': 'colorcloud'},
  'syms': {'colorcloud.core': {'colorcloud.core.foo': ('core.html#foo', 'colorcloud/core.py')}}}
