"""Module to handle loading, preprocessing and postprocessing of the data from [NuScenes](https://www.nuscenes.org/) dataset."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_caesar2020cvpr.ipynb.

# %% auto 0
__all__ = ['NuScenesLidarSegDataset', 'LidarVisualizer', 'NuScenesBEVRenderer']

# %% ../nbs/03_caesar2020cvpr.ipynb 2
from pathlib import Path
import json
import numpy as np
from torch.utils.data import Dataset
from pyquaternion import Quaternion
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.axes import Axes
from matplotlib.patches import Polygon

# %% ../nbs/03_caesar2020cvpr.ipynb 8
class NuScenesLidarSegDataset(Dataset):
    "Load nuScenes LIDAR_TOP point cloud and segmentation data without using the devkit."
    def __init__(self,
                 data_path: str, # Root directory containing the nuScenes dataset files.
                 version: str, # Dataset version to use (e.g., 'v1.0-mini').
                 split: str = 'train', #  Dataset split — 'train', 'val', or 'test'.
                 transform: callable = None # An optional transform function applied to each data sample.
                 ):
        self.data_path = Path(data_path)
        self.version = version
        self.split = split
        self.transform = transform

        # Load metadata
        with open(self.data_path / self.version / 'sample_data.json') as f:
            sample_data = json.load(f)
        with open(self.data_path / self.version / 'lidarseg.json') as f:
            self.lidarseg = json.load(f)
            self.lidarseg_tokens = [item['token'] for item in self.lidarseg]

        with open(self.data_path / self.version / 'category.json') as f:
            self.category = json.load(f)
        with open(self.data_path / self.version / 'colors.json') as f:
            self.color_map = json.load(f)
        self.color_map_rgb_np = np.zeros((len(self.category), 3), dtype=np.uint8)
        for category in self.category:
            index = category['index']
            name = category['name']
            if name in self.color_map:
                self.color_map_rgb_np[index] = self.color_map[name]

        # Get LIDAR_TOP sample entries
        self.lidar_entries = [
            entry for entry in sample_data
            if entry['token'] in self.lidarseg_tokens
        ]

        # Build learning_map_np and content_weights similar to SemanticKITTI
        self.learning_map_np = np.arange(256, dtype=np.uint32)
        self.learning_map_inv_np = np.arange(256, dtype=np.uint32)
        self.content_weights = np.ones(256, dtype=np.float32)

        self.is_test = (split == 'test')

    def set_transform(self,
                      transform: callable): # The transform function to apply.
        "Set a transform function to be applied to each sample."
        self.transform = transform

    def __len__(self):
        """
        Get the total number of samples in the dataset.
        Returns:
            int: Number of samples in the dataset.
        """
        return len(self.lidar_entries)

    def __getitem__(self, idx: int) -> dict:
        """
        Get a single sample from the dataset.
        Args:
            idx (int): Index of the sample to retrieve.
        Returns:
            dict: A dictionary containing:
                - 'frame': Point cloud data (N, 5) where N is the number of points.
                - 'label': Segmentation labels (N,) if available, otherwise None.
                - 'mask': Boolean mask for valid points (N,) if available, otherwise None.
        """
        entry = self.lidar_entries[idx]
        token = entry['token']

        # Load point cloud
        lidar_path = self.data_path / entry['filename']
        frame = np.fromfile(lidar_path, dtype=np.float32).reshape(-1, 5)  # (N, 5)

        # Normalize intensity (divide by 255)
        frame[:, 3] /= 255.0

        label = None
        mask = None
        if not self.is_test:
            label_path = self.data_path / 'lidarseg' / self.version / f'{token}_lidarseg.bin'
            label = np.fromfile(label_path, dtype=np.uint8)
            label = self.learning_map_np[label].astype(np.uint32)

            if label.shape[0] != frame.shape[0]:
                raise ValueError(f"Label count {label.shape[0]} doesn't match point count {frame.shape[0]} for {token}")

            mask = label != 0

        item = {
            'frame': frame,
            'label': label,
            'mask': mask
        }

        if self.transform:
            item = self.transform(item)

        return item

# %% ../nbs/03_caesar2020cvpr.ipynb 39
class LidarVisualizer:
    "A utility class for visualizing LIDAR point clouds and 3D bounding boxes using [Polyscope](https://polyscope.run/)."
    @staticmethod
    def create_box_lines(box: np.ndarray # [center_x, center_y, center_z, width, length, height, rotation_z]
                         )-> tuple: # (corners: (8, 3) array of 3D coordinates of the 8 box corners in global space, lines: (12, 2) array of edge index pairs representing box edges for rendering.)
        "Create 3D bounding box lines from box parameters."
        cx, cy, cz, w, l, h, rot_z = box
        # 8 corners in local box frame - NuScenes convention:
        # x-axis points forward, y-axis points left, z-axis points up
        # width (w) is along y-axis, length (l) is along x-axis, height (h) is along z-axis
        x_corners = np.array([l/2, l/2, -l/2, -l/2, l/2, l/2, -l/2, -l/2])
        y_corners = np.array([w/2, -w/2, -w/2, w/2, w/2, -w/2, -w/2, w/2])
        z_corners = np.array([h/2, h/2, h/2, h/2, -h/2, -h/2, -h/2, -h/2])
        # Rotation (NuScenes rotates around z-axis, but need to consider right-hand rule)
        R = np.array([
            [np.cos(rot_z), -np.sin(rot_z), 0],
            [np.sin(rot_z), np.cos(rot_z), 0],
            [0, 0, 1]
        ])
        corners = np.stack([x_corners, y_corners, z_corners], axis=1)
        corners = (R @ corners.T).T + np.array([cx, cy, cz])
        # 12 lines for box edges
        lines = np.array([
            [0, 1], [1, 2], [2, 3], [3, 0],  # top face
            [4, 5], [5, 6], [6, 7], [7, 4],  # bottom face
            [0, 4], [1, 5], [2, 6], [3, 7]   # verticals
        ])
        return corners, lines

    @staticmethod
    def plot_lidar_with_boxes_polyscope(item: dict, # A dictionary representing one data sample with 'frame', 'boxes', and 'labels', typically from `NuScenesLidarDetDataset.__getitem__`
                                        color_map_rgb_np: np.ndarray = None): # Optional numpy array for label colors (shape: [num_classes, 3] with RGB values in [0, 255] range)
        "Visualizes a LIDAR frame with 3D bounding boxes in an interactive window using Polyscope. "
        frame = item['frame'].copy()  # Make a copy to avoid modifying the original
        boxes = item['boxes']
        labels = item['labels']
        
        ps.init()
        ps.set_up_dir("z_up") # Set Z as the up direction
        ps.remove_all_structures()
        ps_cloud = ps.register_point_cloud("lidar", frame[:, :3], radius=0.001)
        
        # Color by intensity if available, otherwise by height
        if frame.shape[1] > 3:
            intensity = frame[:, 3]  # Assuming 4th column is intensity
            ps_cloud.add_color_quantity("intensity", np.stack([intensity, intensity, intensity], axis=1), enabled=True)
        else:
            # Color by z (height), normalized to [0,1]
            z = frame[:, 2]
            z_min, z_max = z.min(), z.max()
            z_norm = (z - z_min) / (z_max - z_min + 1e-6)
            ps_cloud.add_color_quantity("height", np.stack([z_norm, z_norm, z_norm], axis=1), enabled=True)
        
        # Draw bounding boxes
        for i, box in enumerate(boxes):
            corners, lines = LidarVisualizer.create_box_lines(box)
            color = np.array([1, 0, 0])  # Default color: red
            if color_map_rgb_np is not None:
                label = labels[i]
                if 0 <= label < color_map_rgb_np.shape[0]:
                    color = color_map_rgb_np[label] / 255.0
            ps.register_curve_network(f"box_{i}", corners, lines, color=color, radius=0.0005)
        
        ps.show()

# %% ../nbs/03_caesar2020cvpr.ipynb 43
class NuScenesBEVRenderer:
    """
    `NuScenesBEVRenderer` is a utility for visualizing LIDAR point cloud data and associated 3D bounding boxes in a Bird’s Eye View (BEV) using Matplotlib. It is specifically tailored for use with the nuScenes dataset, following its box conventions for position and orientation.
    The orientation and BEV projection logic in this implementation is adapted from the official [nuScenes devkit](https://github.com/nutonomy/nuscenes-devkit).
    """

    def __init__(self,
                 x_lim: tuple = (-50, 50), # x-axis limits for the BEV plot
                 y_lim: tuple = (-50, 50), # y-axis limits for the BEV plot
                 marker_size: float = 0.2, # Size of the LIDAR points in the BEV plot
                 show_boxes: bool = True, # Whether to draw bounding boxes on the BEV plot
                 show_labels: bool = False, # Whether to show labels on the bounding boxes
                 figsize: tuple = (8, 8)): # Size of the BEV plot figure
        self.x_lim = x_lim
        self.y_lim = y_lim
        self.marker_size = marker_size
        self.show_boxes = show_boxes
        self.show_labels = show_labels
        self.figsize = figsize

    def render(self,
               item: dict, # A dictionary representing one data sample with 'frame', 'boxes', and 'labels', typically from `NuScenesLidarDetDataset.__getitem__`
               color_map_rgb: np.ndarray, # A numpy array for label colors (shape: [num_classes, 3] with RGB values in [0, 255] range)
               category_index_to_name: dict): # A dictionary mapping category indices to names (optional, for labeling boxes)
        "This method plots the LIDAR points in BEV and overlays 2D projections of the 3D bounding boxes."

        frame = item['frame']
        boxes = item['boxes']
        labels = item['labels']

        fig, ax = plt.subplots(figsize=self.figsize)
        ax.set_xlim(self.x_lim)
        ax.set_ylim(self.y_lim)
        ax.set_aspect('equal')

        # Plot LIDAR points
        points_xy = frame[:, :2]
        heights = frame[:, 2]
        ax.scatter(points_xy[:, 0], points_xy[:, 1], c=heights, cmap='viridis', s=self.marker_size, alpha=0.8)

        # Draw bounding boxes
        if self.show_boxes and len(boxes) > 0:
            for box, label in zip(boxes, labels):
                self._draw_box(ax, box, color_map_rgb[label], category_index_to_name.get(label, "unknown"), self.show_labels)


        # remove axis
        ax.axis('off')
        plt.show()

    def _draw_box(self,
                  ax: Axes, # The matplotlib Axes object to draw on
                  box: np.ndarray, # A bounding box in the format [center_x, center_y, center_z, width, length, height, yaw]
                  color: np.ndarray, # RGB color for the box (shape: [3] with values in [0, 255])
                  label: str, # Label for the box (optional, can be used for text annotation)
                  show_label: bool = False): # Whether to show the label text on the box
        "Draw a 2D bounding box using NuScenes box convention: (x, y, z, width, length, height, yaw)"

        cx, cy, _, w, l, _, yaw = box

        # Box corners in local frame (length = x, width = y)
        x_corners = np.array([l/2, l/2, -l/2, -l/2])
        y_corners = np.array([w/2, -w/2, -w/2, w/2])
        corners = np.stack((x_corners, y_corners), axis=1)

        # Rotation
        rot = np.array([
            [np.cos(yaw), -np.sin(yaw)],
            [np.sin(yaw),  np.cos(yaw)]
        ])
        rotated = corners @ rot.T
        translated = rotated + np.array([cx, cy])

        # Draw box
        poly = Polygon(translated, closed=True, edgecolor=color / 255.0, facecolor='none', linewidth=1.5)
        ax.add_patch(poly)

        if show_label:
            ax.text(cx, cy, label, color=color / 255.0, fontsize=8, ha='center', va='center',
                    bbox=dict(facecolor='white', edgecolor='none', alpha=0.6))
