# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_datatools.ipynb.

# %% auto 0
__all__ = ['SemanticKITTIDataset', 'SphericalProjection', 'UnfoldingProjection', 'ProjectionTransform', 'ProjectionVizTransform',
           'ProjectionToTensorTransform']

# %% ../nbs/00_datatools.ipynb 2
import torch
from torch.utils.data import Dataset
from torch import nn
import yaml
from pathlib import Path
import numpy as np

# %% ../nbs/00_datatools.ipynb 4
class SemanticKITTIDataset(Dataset):
    "Load the SemanticKITTI data in a pytorch Dataset object."
    def __init__(self, data_path, is_train=True):
        data_path = Path(data_path)
        yaml_path = data_path/'semantic-kitti.yaml'
        self.velodyne_path = data_path/'data_odometry_velodyne/dataset/sequences'
        self.labels_path = data_path/'data_odometry_labels/dataset/sequences'
        
        velodyne_fns = []
        if is_train: 
            query = '*0[0-9]/velodyne/*.bin'
            velodyne_fns += list(self.velodyne_path.rglob(query))
            query = '*10/velodyne/*.bin'
            velodyne_fns += list(self.velodyne_path.rglob(query))
        else:
            query = '*[12][1-9]/velodyne/*.bin'
            velodyne_fns += list(self.velodyne_path.rglob(query))
            query = '*20/velodyne/*.bin'
            velodyne_fns += list(self.velodyne_path.rglob(query))
        
        self.frame_ids = [fn.stem for fn in velodyne_fns]
        self.frame_sequences = [fn.parts[-3] for fn in velodyne_fns]
        
        with open(yaml_path, 'r') as file:
            metadata = yaml.safe_load(file)
        
        self.labels_dict = metadata.get('labels', {})
        self.learning_map = metadata.get('learning_map', {})
        self.learning_map_inv = metadata.get('learning_map_inv', {})
        self.color_map_bgr = metadata.get('color_map', {})
        
        self.transform = None
        self.is_train = is_train

    def set_transform(self, transform):
        self.transform = transform
    
    def __len__(self):
        return len(self.frame_ids)

    def __getitem__(self, idx):
        frame_id = self.frame_ids[idx]
        frame_sequence = self.frame_sequences[idx]
        
        frame_path = self.velodyne_path/frame_sequence/'velodyne'/(frame_id + '.bin')
        with open(frame_path, 'rb') as f:
            frame = np.fromfile(f, dtype=np.float32).reshape(-1, 4)
        
        label = None
        if self.is_train:
            label_path = self.labels_path/frame_sequence/'labels'/(frame_id + '.label')
            with open(label_path, 'rb') as f:
                label = np.fromfile(f, dtype=np.uint32)
                label = label & 0xFFFF
            label = np.vectorize(self.learning_map.get)(label)
            label = label.astype(int)

        mask = None
        if self.transform:
            frame, label, mask = self.transform(frame, label)
        
        return frame, label, mask

# %% ../nbs/00_datatools.ipynb 8
class SphericalProjection:
    "Calculate yaw and pitch angles for each point and quantize these angles into image grid."
    def __init__(self, fov_up_deg, fov_down_deg, W, H):
        self.fov_up_rad = (fov_up_deg/180.)*np.pi
        self.fov_down_rad = (fov_down_deg/180.)*np.pi
        self.fov_rad = self.fov_up_rad - self.fov_down_rad
        self.W = W
        self.H = H
    
    def get_xy_projections(self, scan_xyz, depth):
        # get angles of all points
        yaw = np.arctan2(scan_xyz[:,1], scan_xyz[:,0])
        pitch = np.arcsin(scan_xyz[:,2] / depth)
        
        # get projections in image coords (between [0.0, 1.0])
        proj_x = 0.5*(1. + yaw/np.pi)
        proj_y = (self.fov_up_rad - pitch)/self.fov_rad

        assert proj_x.min() >= 0.
        assert proj_x.max() <= 1.
        assert proj_y.min() >= 0.
        assert proj_y.min() <= 1.
        
        # scale to image size using angular resolution (between [0.0, W/H])
        proj_x *= self.W
        proj_y *= self.H
        
        # round and clamp to use as indices (between [0, W/H - 1])
        proj_x = np.floor(proj_x)
        proj_x = np.clip(proj_x, 0, self.W - 1).astype(int)
        
        proj_y = np.floor(proj_y)
        proj_y = np.clip(proj_y, 0, self.H - 1).astype(int)
        
        return proj_x, proj_y

# %% ../nbs/00_datatools.ipynb 10
class UnfoldingProjection:
    "Assume the points are sorted in increasing yaw order and line number."
    def __init__(self, W, H, eps=1e-5):
        self.W = W
        self.H = H
        self.eps = eps
    
    def get_xy_projections(self, scan_xyz, depth):
        # get yaw angles of all points
        yaw = np.arctan2(-scan_xyz[:,1], -scan_xyz[:,0])
        
        # clip yaw value between ]-pi, pi[ to avoid numerical erros
        bound = np.pi - self.eps
        yaw = np.clip(yaw, -bound, bound)
        
        # scale to image size
        proj_x  = np.floor(self.W*0.5*(1. - yaw/np.pi)).astype(int)
        
        assert proj_x.min() >= 0
        assert proj_x.max() < self.W
        
        # find discontinuities ("jumps") from scan completing cycle
        jump = abs(yaw[1:] - yaw[:-1]) > 100.*np.pi/180.
        jump = np.concatenate((np.zeros(1), jump))
        
        # every jump indicates a new scan row
        proj_y = jump.cumsum().astype(int)
        
        assert proj_y.max() == self.H - 1
        
        return proj_x, proj_y

# %% ../nbs/00_datatools.ipynb 15
class ProjectionTransform(nn.Module):
    "Pytorch transform that turns a point cloud frame and its respective label into images in given projection style."
    def __init__(self, projection):
        super().__init__()
        self.projection = projection
        self.W = projection.W
        self.H = projection.H
        
    def forward(self, frame, label):
        # get point_cloud components
        scan_xyz = frame[:,:3]
        reflectance = frame[:, 3]

        assert reflectance.max() <= 1.
        assert reflectance.min() >= 0.

        # get depths of all points
        depth = np.linalg.norm(scan_xyz, 2, axis=1)

        # get projections
        proj_x, proj_y = self.projection.get_xy_projections(scan_xyz, depth)
        
        # order in decreasing depth
        order = np.argsort(depth)[::-1]
        info_list = [
            scan_xyz,
            reflectance[..., np.newaxis],
            depth[..., np.newaxis]
        ]
        if label is not None:
            info_list += [label[..., np.newaxis]]
            
        scan_info = np.concatenate(info_list, axis=-1)
        scan_info = scan_info[order]
        proj_y = proj_y[order]
        proj_x = proj_x[order]
        
        # setup the image tensor
        projections_img = np.zeros((self.H, self.W, 2+len(info_list)))
        projections_img[:,:,-1] -= 1 # this helps to identify points in the projection with no lidar readings
        projections_img[proj_y, proj_x] = scan_info
        
        if label is not None:
            # frame image
            frame_img = projections_img[:,:,:-1]
            # label image
            label_img = projections_img[:,:,-1].astype(int)
        else:
            frame_img = projections_img
            label_img = None
        # mask image
        mask_img = projections_img[:,:,-1]>=0
        
        return frame_img, label_img, mask_img

# %% ../nbs/00_datatools.ipynb 16
class ProjectionVizTransform(nn.Module):
    "Pytorch transform to preprocess projection images for proper visualization."
    def __init__(self, color_map_bgr, learning_map_inv):
        super().__init__()
        self.learning_map_inv_np = np.zeros((len(learning_map_inv),))
        for k, v in learning_map_inv.items():
            self.learning_map_inv_np[k] = v
        
        max_key = sorted(color_map_bgr.keys())[-1]
        self.color_map_rgb_np = np.zeros((max_key+1, 3))
        for k, v in color_map_bgr.items():
            self.color_map_rgb_np[k] = np.array(v[::-1], np.float32)
    
    def normalize(self, img, min_value, max_value):
        assert img.max() <= max_value
        assert img.min() >= min_value
        assert max_value > min_value
        
        img = img.clip(min_value, max_value)
        return (255.*(img - min_value)/(max_value - min_value)).astype(int)
    
    def forward(self, frame_img, label_img, mask_img):
        x = self.normalize(frame_img[:,:,0], -100., 100.)
        y = self.normalize(frame_img[:,:,1], -100., 100.)
        z = self.normalize(frame_img[:,:,2], -31., 5.)
        r = self.normalize(frame_img[:,:,3], 0., 1.)
        d = self.normalize(frame_img[:,:,4], 0., 100.)
        normalized_frame_img = np.stack((x, y, z, r, d), axis=-1)
        normalized_frame_img[mask_img == False] *= 0

        colored_label_img = None
        if label_img is not None:
            label_img[mask_img] = self.learning_map_inv_np[label_img[mask_img]]
            colored_label_img = np.zeros(label_img.shape + (3,))
            colored_label_img[mask_img] = self.color_map_rgb_np[label_img[mask_img]]
            colored_label_img = colored_label_img.astype(int)
        
        return normalized_frame_img, colored_label_img, mask_img

# %% ../nbs/00_datatools.ipynb 23
class ProjectionToTensorTransform(nn.Module):
    "Pytorch transform that converts the projections from np.array to torch.tensor. It also changes the frame image format from (H, W, C) to (C, H, W)."
    def forward(self, frame_img, label_img, mask_img):
        frame_img = np.transpose(frame_img, (2, 0, 1))
        frame_img = torch.from_numpy(frame_img).float()
        label_img = torch.from_numpy(label_img)
        mask_img = torch.from_numpy(mask_img)
        return frame_img, label_img, mask_img
